# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- none

pool:
  vmImage: 'macos-latest'

steps:
- task: Xcode@5
  inputs:
    actions: 'build'
    configuration: 'Release'
    sdk: 'iphoneos'
    xcWorkspacePath: 'CineRater/CineRater.xcodeproj'
    scheme: 'CineRater DEV'
    packageApp: true
    signingOption: 'default'
    destinationPlatformOption: 'iOS'
    destinationSimulators: 'iPhone 14 Pro Max'
