# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- none

pool:
  vmImage: 'macos-latest'

steps:
- task: Xcode@5
  inputs:
    actions: 'clean build'
    configuration: 'Release'
    sdk: 'iphoneos'
    xcWorkspacePath: 'CineRater/CineRater.xcodeproj'
    scheme: 'CineRater DEV'
    packageApp: false
    publishJUnitResults: true
    destinationPlatformOption: 'iOS'
    destinationSimulators: 'iPhone 14 Pro Max'

- task: PowerShell@2
  displayName: 'Unit test & Code coverage'
  inputs:
    targetType: 'inline'
    script: |
      brew install fastlane && fastlane generate_code_coverage

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'CineRater_Service'
    organization: 'sawpyaeyadanar'
    scannerMode: 'CLI'
    configMode: 'file'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'