pool:
- task: Xcode@5
  inputs:
    actions: 'build'
    packageApp: true
    signingOption: 'auto'
    teamId: 'YE28Y3LX8V'
    destinationPlatformOption: 'iOS'
  vmImage: 'macos-latest'

steps:
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: ''
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default' # Options: 10, 11, 12, 13, 14, default, specifyPath