trigger:
 branches:
    include:
      - main


schedules:

#- cron: "* 10 * * *" //cron-like schedule pattern
- cron: "0 15 10 ? * *" #Fire at 10:15 a.m. every day
  always: true
  displayName: Daily midnight build (UTC 16:00)
  branches:
    include:
     - sit
     
pool:
  vmImage: 'macos-latest'

steps:
- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: ''
    sdk: 'iphoneos'
    configuration: 'Release'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default' # Options: 10, 11, 12, 13, 14, default, specifyPath
