# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
  branches:
    include:
    - master
    - develop

pool:
  vmImage: 'macos-13'

steps:
- script: |
   xcodebuild -showsdks
   
   echo "=====================XCode Path ============================"
   
   sudo xcode-select -switch /Applications/Xcode.app/Contents/Developer
   
   xcodebuild -showsdks
  displayName: 'Command Line Script'

#steps:
- task: Xcode@5
  displayName: 'Use this task to build, test, or archive an Xcode workspace on macOS, and optionally package an app.'
  inputs:
    actions: 'clean build'
    configuration: 'Release'
    sdk: 'iphoneos'
    xcWorkspacePath: 'CineRater/CineRater.xcodeproj'
    scheme: 'CineRater DEV'
    xcodeVersion: '15'
    #xcodeVersion: 'specifyPath'
    #xcodeDeveloperDir: '/Applications/Xcode.app'
    packageApp: false
    publishJUnitResults: true
    #destinationPlatformOption: 'iOS'
    #destinationSimulators: 'iPhone 14 Pro Max'

- task: PowerShell@2
  displayName: 'Unit test & Code coverage'
  inputs:
    targetType: 'inline'
    script: |
      brew install fastlane && fastlane generate_code_coverage

- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'CineRater_Service'
    organization: 'sawpyaeyadanar'
    scannerMode: 'CLI'
    configMode: 'file'

- task: SonarCloudAnalyze@1

- task: SonarCloudPublish@1
  inputs:
    pollingTimeoutSec: '300'
