
default_platform(:ios)

platform :ios do

#desc "Description of what the lane does"
#lane :tests do
#  puts "Hello World"
#end

lane :tests do
  run_tests(project: "CineRater/CineRater.xcodeproj",scheme: "CineRater")
end

  lane :unit_test do |options|
    ENV['FASTLANE_XCODE_LIST_TIMEOUT'] = '600'
    scan(
        #workspace: "FindYourSpace.xcworkspace",
        scheme: "CineRater",
        test_without_building: false,
        result_bundle: true,
        code_coverage: true,
        output_directory: "Build/Logs/Test/",
    )
  end
  
  lane :generate_code_coverage do |options|
    sh "bash ../xccov-to-sonarqube-generic.sh ../Build/Logs/Test/CineRater.xcresult > ./sonarqube-generic-coverage.xml"
  end
 end
 
 lane :beta do
  build_app(scheme: "CineRater")
end

# Builds and packages iOS apps. It takes care of all the heavy lifting and generate a signed ipa or app file
  desc "Builds and packages app"
  lane :export do
    gym(
      project: "CineRater/CineRater.xcodeproj",
      # Target you are exporting
      scheme: "CineRater",
      # Hide all information that's not necessary while building
      silent: false,
      # Clean the project before uploading it
      clean: true,
      # Uses Automatic manage signing - This is toggled on Xcode under Signing and capabilities.
      export_xcargs: "-allowProvisioningUpdates",
      output_name: "ReleaseApp.ipa"
    )
  end
